config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :addresses, only: [:new, :create, :index]
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index 
    if Address.count > 0
      @addresses = Address.last
    else
      @addresses = Address.new
      flash[:error] = '<strong>Could not retrieve: </strong> no data has been saved.'
    end
  end 

  def new 
    @address = Address.new
  end 

  def create 
    @address = Address.create(address_params)
    if @address.invalid?
      flash[:error] = '<strong>Could not save: </strong> the data you entered is invalid.'
    else
      redirect_to addresses_path
    end
    # redirect_to root_path
  end 

  private 

  def address_params
    params.require(:address).permit(:street, :city, :state, :zip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    puts ""
  end

  def index
      @address = Address.last
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end
 
  def create 
    @address = Address.create(address_params)
    if @address.valid?
      redirect_to root_path
    else 
      render :new, status: :unprocessable_entity
    end
  end
  

  private

  def address_params
    params.required(:address).permit(:street, :city, :state, :zip)
  end

end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/addresses/index.html.erb
<div class="booyah-box col-10 offset-1"> 
   
     <p> <%= @addresses.street %></p>

      <p><%= @addresses.city %></p>

      <p><%= @addresses.state %></p>

      <%= @addresses.zip %>
</div>

app/views/addresses/new.html.erb
<div class="booyah-box col-10 offset-1">
    <%= simple_form_for @address do |f| %>
     <%= f.error_notification %>
      <%= f.input :street %>

      <%= f.input :city %>

      <%= f.input :state %>

      <%= f.input :zip %>

      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    

    <nav class="navbar navbar-toggleable-md navbar-dark bg-primary">
      <%= link_to 'Quiz 1', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
           <%= link_to new_address_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            Quiz 2 Submit
           <% end %>
          </li>
        </ul>
      </div>      
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
           <%= link_to addresses_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            Quiz 2 Retrieve
           <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>

      
</html>

app/views/pages/home.html.erb
<html>
<head> 
<title>Quiz 1</title>
</head>

<body bgcolor="#f1f1f1" text="Red">

<h1 class='quiz2'>&nbsp;&nbsp;Quiz 1: Web Development Pipeline</h1>
<h4 class='quiz2'>&nbsp;&nbsp;&nbsp;&nbsp;Build a new web application from scratch and make sure it satisfies the following criteria:
</h4>
<ul>
  <li>This should be a rails application, not a plain HTML page.</li>
  <li>The web application has a page with static content on it</li>
  <li>The web application is hosted on Heroku.</li>
  <li>The code for the application is hosted on GitHub.</li>
  <li>There is a headline on the page of the application that is a non-black color.
  </li>

</body>
</html>

app/views/pages/new.html.erb
    
<div class="booyah-box col-10 offset-1">
  <button class="btn btn-sm btn-bootstrap" data-fill="bootstrap" data-tooltip title="Fill form with valid data">Fill</button>
    <%= simple_form_for @address do |f| %>
     <%= f.error_notification %>
      
      <%= f.input :street %>

      <%= f.input :city %>

      <%= f.input :state %>

      <%= f.input :zip %>

      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
</div>